version: '2'

services:
  car-api:  
    network_mode: host
    ports:
      - "30002:30002"
    restart: unless-stopped
    container_name: car-api
    volumes:
      - ./config/config.yml:/config/config.yml
    build:
      context: .
      dockerfile: Dockerfile
    command: go run /app/cmd/api/main.go

  postgres:
    image: postgres:15
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'psql -d api_car_share -U postgres -c "select 1"']
      interval: 5s
      retries: 10
